 load("govbonds.RData")
ns_res <- estim_nss(govbonds, c("GERMANY", "AUSTRIA", "FRANCE"),matrange = c(0,30), method = "ns", deltatau = 0.2)
print(ns_res)
plot(ns_res)
summary(ns_res)

sv_res <- estim_nss(govbonds, c("GERMANY"),matrange = c(0,30), method = "sv", deltatau = 1)
print(sv_res)
plot(sv_res)
summary(sv_res)
